import {useEffect,useState} from "react";
import NavMenu from "./NavMenu";
const age=(t?:string)=>{if(!t)return"age unknown";const s=Math.max(0,(Date.now()-new Date(t).getTime())/1000);if(s<2)return"just now";if(s<60)return`${Math.floor(s)}s old`;if(s<3600)return`${Math.floor(s/60)}m old`;if(s<86400)return`${Math.floor(s/3600)}h old`;return`${Math.floor(s/86400)}d old`};
const Age=({t}:{t?:string})=><small className="age" title={t?new Date(t).toLocaleString():"No timestamp"}>{age(t)}</small>;
export default function EntityProfilePage(){
 const id=decodeURIComponent(window.location.pathname.split("/").pop()||"");const[data,setData]=useState<any>(null),[error,setError]=useState("");const[tick,setTick]=useState(0);
 useEffect(()=>{fetch(`/api/v1/entities/${encodeURIComponent(id)}/profile`).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(setData).catch(e=>setError(String(e)))},[id]);useEffect(()=>{const x=setInterval(()=>setTick(v=>v+1),1000);return()=>clearInterval(x)},[]);
 if(error)return <div className="profilePage"><div className="errorBanner">{error}</div></div>;if(!data)return <div className="profilePage">Loading profile…</div>;
 const e=data.entity,c=e.components||{},times=e.component_times||{},name=c.aliases?.name||e.entity_id,loc=c.location||{},caps=c.capabilities?.available||[];
 const Row=({label,value,component}:{label:string,value:any,component:string})=><><dt>{label}</dt><dd>{value??"—"}<Age t={times[component]||e.updated_at}/></dd></>;
 return <div className="adminShell"><header><NavMenu active="map"/><div/></header><div className="profilePage"><div className="profileHero"><div><div className="panelTitle">ENTITY PROFILE</div><h1>{name}</h1><div className="tags"><span>{e.template}</span><span>{e.is_live?"LIVE":"OFFLINE"}</span></div></div><a className="quiet buttonLink" href="/">Map</a></div><div className="profileGrid"><section><h3>Overview</h3><dl><Row label="ID" value={e.entity_id} component="aliases"/><Row label="Revision" value={e.revision} component="provenance"/><Row label="Entity update" value={new Date(e.updated_at).toLocaleString()} component="provenance"/><Row label="Source" value={c.provenance?.source_system||(Object.values(e.component_provenance||{})[0] as any)?.source_system} component="provenance"/></dl></section><section><h3>Current state</h3><dl><Row label="Status" value={c.status?.state||c.operational_state?.state} component={c.status?"status":"operational_state"}/><Row label="Latitude" value={loc.latitude} component="location"/><Row label="Longitude" value={loc.longitude} component="location"/><Row label="Speed" value={loc.speed_mps==null?null:`${loc.speed_mps} m/s`} component="location"/></dl></section><section><h3>Capabilities</h3><Age t={times.capabilities||e.updated_at}/><div className="chips">{caps.length?caps.map((x:any)=><span key={x.name||x}>{x.name||x}</span>):<small>None advertised</small>}</div></section><section><h3>Artifacts ({data.artifacts.length})</h3>{data.artifacts.length?data.artifacts.map((x:any)=><a className="relatedRow" href={`/artifacts?artifact=${x.artifact_id}`} target="_blank" rel="noreferrer" key={x.artifact_id}><strong>{x.name}</strong><small>{x.artifact_type} · {age(x.created_at)}</small></a>):<small>No related artifacts</small>}</section><section className="wide"><h3>All related Tasks ({data.tasks.length})</h3>{data.tasks.length?data.tasks.map((x:any)=><div className="relatedRow" key={x.task_id}><strong>{x.specification?.type?.split(".").pop()}</strong><small>{x.status} · priority {x.priority} · {age(x.updated_at||x.created_at)}</small></div>):<small>No related tasks</small>}</section><section className="wide"><h3>Components</h3>{Object.entries(c).map(([k,v])=><div key={k}><h4>{k} <Age t={times[k]||e.updated_at}/></h4><pre>{JSON.stringify(v,null,2)}</pre></div>)}</section></div></div></div>
}