import {useEffect,useState} from "react";
import NavMenu from "./NavMenu";
export default function EntityProfilePage(){
 const id=decodeURIComponent(window.location.pathname.split("/").pop()||""); const[data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/v1/entities/${encodeURIComponent(id)}/profile`).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(setData).catch(e=>setError(String(e)))},[id]);
 if(error)return <div className="adminShell"><header><NavMenu active="map"/><div/></header><div className="adminPage"><div className="errorBanner">{error}</div></div></div>;
 if(!data)return <div className="adminShell"><header><NavMenu active="map"/><div/></header><div className="adminPage">Loading profile…</div></div>;
 const e=data.entity,c=e.components||{},name=c.aliases?.name||e.entity_id,loc=c.location||{},caps=c.capabilities?.available||[];
 return <div className="adminShell"><header><NavMenu active="map"/><div/></header><div className="profilePage"><div className="profileHero"><div><div className="panelTitle">ENTITY PROFILE</div><h1>{name}</h1><div className="tags"><span>{e.template}</span><span>{e.is_live?"LIVE":"OFFLINE"}</span></div></div><a className="quiet buttonLink" href="/">Back to map</a></div><div className="profileGrid"><section><h3>Overview</h3><dl><dt>ID</dt><dd>{e.entity_id}</dd><dt>Revision</dt><dd>{e.revision}</dd><dt>Updated</dt><dd>{new Date(e.updated_at).toLocaleString()}</dd><dt>Source</dt><dd>{c.provenance?.source_system||(Object.values(e.component_provenance||{})[0] as any)?.source_system||"—"}</dd></dl></section><section><h3>Current state</h3><dl><dt>Status</dt><dd>{c.status?.state||c.operational_state?.state||"—"}</dd><dt>Latitude</dt><dd>{loc.latitude??"—"}</dd><dt>Longitude</dt><dd>{loc.longitude??"—"}</dd><dt>Speed</dt><dd>{loc.speed_mps??"—"} m/s</dd></dl></section><section><h3>Capabilities</h3><div className="chips">{caps.length?caps.map((x:any)=><span key={x.name||x}>{x.name||x}</span>):<small>None advertised</small>}</div></section><section><h3>Related artifacts</h3>{data.artifacts.length?data.artifacts.map((x:any)=><a className="relatedRow" href="/artifacts" key={x.artifact_id}><strong>{x.name}</strong><small>{x.artifact_type}</small></a>):<small>No related artifacts</small>}</section><section className="wide"><h3>Recent tasks</h3>{data.tasks.length?data.tasks.map((x:any)=><div className="relatedRow" key={x.task_id}><strong>{x.specification?.type?.split(".").pop()}</strong><small>{x.status} · priority {x.priority}</small></div>):<small>No related tasks</small>}</section><section className="wide"><h3>Components</h3><pre>{JSON.stringify(c,null,2)}</pre></section></div></div></div>
}
