
import {useEffect,useState} from "react";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
type Artifact={artifact_id:string;name:string;artifact_type:string;content_type:string;size_bytes:number;sha256:string;related_plugin_id?:string;created_at:string};
export default function ArtifactsPage(){
 const[a,setA]=useState<Artifact[]>([]),[selected,setSelected]=useState<Artifact|null>(null);
 const[name,setName]=useState("note.txt"),[content,setContent]=useState("OpenGrid Artifact\n"),[error,setError]=useState("");
 const load=async()=>{try{const r=await fetch(`${API}/api/v1/artifacts`);if(!r.ok)throw new Error(await r.text());setA(await r.json());setError("")}catch(e:any){setError(String(e?.message||e))}};
 useEffect(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[]);
 const create=async()=>{const r=await fetch(`${API}/api/v1/artifacts/text`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,artifact_type:"TEXT",content_type:"text/plain",content})});if(!r.ok){setError(await r.text());return}const created=await r.json();setA(p=>[created,...p]);setSelected(created);setError("")};
 return <div className="adminShell"><header><div className="brand"><span>△</span> OPENGRID</div><nav className="topNav"><a href="/">Map</a><a href="/plugins">Plugins</a><a className="active" href="/artifacts">Artifacts</a></nav><div/></header><div className="adminPage"><section className="adminList"><div className="panelTitle">ARTIFACTS</div>{error&&<div className="errorBanner">{error}</div>}{a.length===0&&<div className="emptyState">No Artifacts yet. Create the first one using the form.</div>}{a.map(x=><button className={`artifactCard ${selected?.artifact_id===x.artifact_id?"selected":""}`} key={x.artifact_id} onClick={()=>setSelected(x)}><strong>{x.name}</strong><small>{x.artifact_type} · {x.size_bytes} bytes</small><code>{x.sha256.slice(0,16)}…</code></button>)}</section><section className="adminDetail">{selected?<><div className="panelTitle">ARTIFACT</div><h2>{selected.name}</h2><pre>{JSON.stringify(selected,null,2)}</pre><a className="downloadButton" href={`${API}/api/v1/artifacts/${selected.artifact_id}/content`}>Download</a></>:<><div className="panelTitle">CREATE ARTIFACT</div><h2>Text Artifact</h2><p>This intentionally small integration stores text in MinIO and metadata in PostgreSQL.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Content<textarea value={content} onChange={e=>setContent(e.target.value)}/></label><button className="primary" onClick={create}>Create Artifact</button></>}</section></div></div>
}
