import {useEffect,useMemo,useRef,useState} from 'react'; import maplibregl,{Map,Marker} from 'maplibre-gl';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Entity={entity_id:string;revision:number;template:string;components:Record<string,any>;updated_at:string};
const mc=(t:string)=>t==='ASSET'?'marker asset':t==='FUSED_TRACK'?'marker fused':'marker track';
export default function App(){
 const mapDiv=useRef<HTMLDivElement>(null), map=useRef<Map|null>(null), markers=useRef<Record<string,Marker>>({});
 const [entities,setEntities]=useState<Entity[]>([]),[selected,setSelected]=useState<Entity|null>(null),[filter,setFilter]=useState('');
 useEffect(()=>{if(!mapDiv.current||map.current)return; map.current=new maplibregl.Map({container:mapDiv.current,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[-71.305,41.498],zoom:12}); map.current.addControl(new maplibregl.NavigationControl(),'bottom-right')},[]);
 useEffect(()=>{const load=async()=>{const r=await fetch(`${API}/api/v1/entities`);if(r.ok)setEntities(await r.json())};load();const x=setInterval(load,1500);return()=>clearInterval(x)},[]);
 useEffect(()=>{if(!map.current)return;for(const e of entities){const l=e.components?.location;if(l?.latitude==null||l?.longitude==null)continue;let m=markers.current[e.entity_id];if(!m){const el=document.createElement('button');el.className=mc(e.template);el.title=e.components?.aliases?.name||e.entity_id;el.onclick=()=>setSelected(e);m=new maplibregl.Marker({element:el}).setLngLat([l.longitude,l.latitude]).addTo(map.current!);markers.current[e.entity_id]=m}else{m.setLngLat([l.longitude,l.latitude]);m.getElement().onclick=()=>setSelected(e)}}},[entities]);
 const visible=useMemo(()=>{const q=filter.toLowerCase();return entities.filter(e=>!q||e.entity_id.toLowerCase().includes(q)||(e.components?.aliases?.name||'').toLowerCase().includes(q)||e.template.toLowerCase().includes(q))},[entities,filter]);
 return <div className="shell"><header><div className="brand"><span>△</span> COMMONGRID</div><div className="status"><i/> LIVE</div></header><aside className="left"><div className="panelTitle">ENTITIES</div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search entities"/><div className="entityList">{visible.map(e=><button key={e.entity_id} className={`entityRow ${selected?.entity_id===e.entity_id?'selected':''}`} onClick={()=>setSelected(e)}><b className={`entityGlyph ${e.template.toLowerCase()}`}/><span><strong>{e.components?.aliases?.name||e.entity_id}</strong><small>{e.template} · rev {e.revision}</small></span></button>)}</div></aside><main ref={mapDiv}/><aside className="right">{!selected?<div className="empty"><div>⌖</div>Select an entity</div>:<><div className="panelTitle">ENTITY DETAILS</div><h2>{selected.components?.aliases?.name||selected.entity_id}</h2><span className="tag">{selected.template}</span><section><h3>Identity</h3><dl><dt>ID</dt><dd>{selected.entity_id}</dd><dt>Revision</dt><dd>{selected.revision}</dd><dt>Source</dt><dd>{selected.components?.provenance?.source_system||'—'}</dd></dl></section><section><h3>Location</h3><dl><dt>Latitude</dt><dd>{selected.components?.location?.latitude?.toFixed?.(6)||'—'}</dd><dt>Longitude</dt><dd>{selected.components?.location?.longitude?.toFixed?.(6)||'—'}</dd><dt>Heading</dt><dd>{selected.components?.location?.heading_degrees??'—'}°</dd><dt>Speed</dt><dd>{selected.components?.location?.speed_mps??'—'} m/s</dd></dl></section>{selected.template==='FUSED_TRACK'&&<section className="fusionBox"><h3>Fusion</h3><dl><dt>Confidence</dt><dd>{selected.components?.provenance?.confidence}</dd><dt>Separation</dt><dd>{selected.components?.fusion?.separation_m} m</dd></dl><div className="sources">{(selected.components?.relationships?.derived_from||[]).map((x:string)=><code key={x}>{x}</code>)}</div></section>}<section><h3>Raw components</h3><pre>{JSON.stringify(selected.components,null,2)}</pre></section></>}</aside></div>
}
