import {useEffect,useState} from "react";
import NavMenu from "./NavMenu";
const API="";
type Plugin={plugin_id:string;name:string;version:string;plugin_type:string;protocol?:string;enabled:boolean;status:string;status_message?:string;metrics:Record<string,any>;configuration:Record<string,any>;last_heartbeat?:string};
type Camera={id:string;name:string;enabled:boolean;latitude:number;longitude:number;altitude_m:number;direction_deg:number;horizontal_fov_deg:number;vertical_fov_deg:number;range_m:number;snapshot_url:string;stream_url:string;stream_type:string};
const blankCamera=():Camera=>({id:`camera-${Date.now()}`,name:"New Fixed Camera",enabled:true,latitude:41.49,longitude:-71.315,altitude_m:5,direction_deg:0,horizontal_fov_deg:60,vertical_fov_deg:35,range_m:500,snapshot_url:"",stream_url:"",stream_type:"HLS"});
export default function PluginsPage(){
 const[plugins,setPlugins]=useState<Plugin[]>([]),[selected,setSelected]=useState<Plugin|null>(null),[logs,setLogs]=useState<any[]>([]),[error,setError]=useState(""),[form,setForm]=useState<Record<string,any>>({}),[saving,setSaving]=useState(false),[cameraIndex,setCameraIndex]=useState(0);
 const load=async()=>{try{const r=await fetch(`${API}/api/v1/plugins`);if(!r.ok)throw new Error(await r.text());const items=await r.json();setPlugins(items);if(selected){const x=items.find((p:Plugin)=>p.plugin_id===selected.plugin_id);if(x)setSelected(x)}setError("")}catch(e:any){setError(String(e?.message||e))}};
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(selected){setForm({...selected.configuration});setCameraIndex(0)}},[selected?.plugin_id]);
 const pick=async(p:Plugin)=>{setSelected(p);setForm({...p.configuration});const r=await fetch(`${API}/api/v1/plugins/${p.plugin_id}/logs`);if(r.ok)setLogs(await r.json())};
 const save=async()=>{if(!selected)return;setSaving(true);const r=await fetch(`${API}/api/v1/plugins/${selected.plugin_id}/configuration`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({configuration:form})});setSaving(false);if(!r.ok)return setError(await r.text());const u=await r.json();setSelected(u);setPlugins(p=>p.map(x=>x.plugin_id===u.plugin_id?u:x));setError("")};
 const toggle=async()=>{if(!selected)return;const r=await fetch(`${API}/api/v1/plugins/${selected.plugin_id}/${selected.enabled?"disable":"enable"}`,{method:"POST"});if(r.ok){setSelected(await r.json());load()}};
 const cameras:Camera[]=Array.isArray(form.cameras)?form.cameras:[]; const cam=cameras[cameraIndex];
 const setCam=(patch:Partial<Camera>)=>setForm({...form,cameras:cameras.map((c,i)=>i===cameraIndex?{...c,...patch}:c)});
 const addCam=()=>{const next=[...cameras,blankCamera()];setForm({...form,cameras:next});setCameraIndex(next.length-1)};
 const delCam=()=>{const next=cameras.filter((_,i)=>i!==cameraIndex);setForm({...form,cameras:next});setCameraIndex(Math.max(0,Math.min(cameraIndex,next.length-1)))};
 const isCamera=selected?.protocol==="CAMERA";
 return <div className="adminShell"><header><NavMenu active="plugins"/><div/></header><div className="adminPage"><section className="adminList"><div className="panelTitle">PLUGINS</div><button className="quiet refreshButton" onClick={load}>Refresh registry</button>{error&&<div className="errorBanner">{error}</div>}{plugins.map(p=><button className={`pluginCard ${selected?.plugin_id===p.plugin_id?"selected":""}`} key={p.plugin_id} onClick={()=>pick(p)}><div><strong>{p.name}</strong><small>{p.protocol||p.plugin_type} · v{p.version}</small></div><span className={`pluginStatus ${p.enabled?p.status.toLowerCase():"disabled"}`}>{p.enabled?p.status:"DISABLED"}</span><dl><dt>Entities</dt><dd>{p.metrics?.entities_active??0}</dd><dt>Errors</dt><dd>{p.metrics?.parse_errors??0}</dd></dl></button>)}</section><section className="adminDetail">{!selected?<div className="empty"><div>◫</div>Select a plugin</div>:<><div className="panelTitle">PLUGIN DETAILS</div><h2>{selected.name}</h2><div className="tags"><span>{selected.plugin_type}</span><span>{selected.protocol}</span><span>{selected.status}</span></div>
 {isCamera?<section><div className="sectionHeading"><h3>Configured cameras</h3><button className="quiet" onClick={addCam}>+ Add camera</button></div><div className="cameraTabs">{cameras.map((c,i)=><button key={`${c.id}-${i}`} className={i===cameraIndex?"selected":""} onClick={()=>setCameraIndex(i)}>{c.name||c.id}</button>)}</div>{cam?<><div className="configGrid"><label>Name<input value={cam.name} onChange={e=>setCam({name:e.target.value})}/></label><label>Entity ID<input value={cam.id} onChange={e=>setCam({id:e.target.value})}/></label><label>Latitude<input type="number" step="0.000001" value={cam.latitude} onChange={e=>setCam({latitude:Number(e.target.value)})}/></label><label>Longitude<input type="number" step="0.000001" value={cam.longitude} onChange={e=>setCam({longitude:Number(e.target.value)})}/></label><label>Altitude (m)<input type="number" value={cam.altitude_m} onChange={e=>setCam({altitude_m:Number(e.target.value)})}/></label><label>Direction (° true)<input type="number" min="0" max="359" value={cam.direction_deg} onChange={e=>setCam({direction_deg:Number(e.target.value)})}/></label><label>Horizontal FOV (°)<input type="number" min="1" max="180" value={cam.horizontal_fov_deg} onChange={e=>setCam({horizontal_fov_deg:Number(e.target.value)})}/></label><label>Vertical FOV (°)<input type="number" min="1" max="180" value={cam.vertical_fov_deg} onChange={e=>setCam({vertical_fov_deg:Number(e.target.value)})}/></label><label>View range (m)<input type="number" min="1" value={cam.range_m} onChange={e=>setCam({range_m:Number(e.target.value)})}/></label><label>Stream type<select value={cam.stream_type} onChange={e=>setCam({stream_type:e.target.value})}><option>HLS</option><option>MP4</option><option>MJPEG</option><option>IMAGE</option></select></label></div><label>Live stream URL<input value={cam.stream_url} onChange={e=>setCam({stream_url:e.target.value})}/></label><label>Snapshot URL (optional)<input value={cam.snapshot_url} onChange={e=>setCam({snapshot_url:e.target.value})}/></label><label className="switchRow"><input type="checkbox" checked={cam.enabled!==false} onChange={e=>setCam({enabled:e.target.checked})}/> Camera enabled</label><div className="adminActions"><button className="danger" onClick={delCam}>Delete camera</button><button className="primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save cameras"}</button></div><small>Changes are picked up by the adapter automatically; no Docker restart is required.</small></>:<div className="empty">No cameras configured.</div>}</section>:<section><h3>Configuration</h3><textarea className="missionEditor" value={JSON.stringify(form,null,2)} onChange={e=>{try{setForm(JSON.parse(e.target.value));setError("")}catch{setError("Configuration must be valid JSON")}}}/><button className="primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save configuration"}</button></section>}
 <section><h3>Metrics</h3><pre>{JSON.stringify(selected.metrics,null,2)}</pre></section><div className="adminActions"><button className={selected.enabled?"danger":"primary"} onClick={toggle}>{selected.enabled?"Disable":"Enable"}</button><button className="quiet" onClick={()=>pick(selected)}>Refresh logs</button></div><section><h3>Logs</h3><div className="logList">{logs.length?logs.map(l=><div className="logRow" key={l.log_id}><strong>{l.level}</strong><span>{l.message}</span><small>{l.created_at}</small></div>):<small>No plugin logs yet.</small>}</div></section></>}</section></div></div>
}
