import {useEffect,useState} from "react";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
type Plugin={plugin_id:string;name:string;version:string;plugin_type:string;protocol?:string;enabled:boolean;status:string;status_message?:string;metrics:Record<string,any>;configuration:Record<string,any>;last_heartbeat?:string};
export default function PluginsPage(){
 const [plugins,setPlugins]=useState<Plugin[]>([]),[selected,setSelected]=useState<Plugin|null>(null),[logs,setLogs]=useState<any[]>([]),[text,setText]=useState("AIS diagnostic sample\n");
 const load=()=>fetch(`${API}/api/v1/plugins`).then(r=>r.json()).then(setPlugins);
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 const pick=async(p:Plugin)=>{setSelected(p);const r=await fetch(`${API}/api/v1/plugins/${p.plugin_id}/logs`);if(r.ok)setLogs(await r.json())};
 const toggle=async()=>{if(!selected)return;const a=selected.enabled?"disable":"enable";const r=await fetch(`${API}/api/v1/plugins/${selected.plugin_id}/${a}`,{method:"POST"});if(r.ok){const u=await r.json();setSelected(u);load()}};
 const artifact=async()=>{if(!selected)return;const r=await fetch(`${API}/api/v1/artifacts/text`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:`diagnostic-${Date.now()}.txt`,artifact_type:"DIAGNOSTIC_TEXT",content_type:"text/plain",content:text,related_plugin_id:selected.plugin_id})});if(r.ok)window.location.href="/artifacts";else alert(await r.text())};
 return <div className="adminShell"><header><div className="brand"><span>△</span> OPENGRID</div><nav className="topNav"><a href="/">Map</a><a className="active" href="/plugins">Plugins</a><a href="/artifacts">Artifacts</a></nav><div/></header><div className="adminPage"><section className="adminList"><div className="panelTitle">PLUGINS</div>{plugins.map(p=><button className={`pluginCard ${selected?.plugin_id===p.plugin_id?"selected":""}`} key={p.plugin_id} onClick={()=>pick(p)}><div><strong>{p.name}</strong><small>{p.protocol||p.plugin_type} · v{p.version}</small></div><span className={`pluginStatus ${p.enabled?p.status.toLowerCase():"disabled"}`}>{p.enabled?p.status:"DISABLED"}</span><dl><dt>Messages</dt><dd>{p.metrics?.messages_received??0}</dd><dt>Entities</dt><dd>{p.metrics?.entities_active??0}</dd><dt>Errors</dt><dd>{p.metrics?.parse_errors??0}</dd></dl></button>)}</section><section className="adminDetail">{!selected?<div className="empty"><div>◫</div>Select a plugin</div>:<><div className="panelTitle">PLUGIN DETAILS</div><h2>{selected.name}</h2><div className="tags"><span>{selected.plugin_type}</span><span>{selected.protocol}</span><span>{selected.status}</span></div><section><h3>Configuration</h3><pre>{JSON.stringify(selected.configuration,null,2)}</pre></section><section><h3>Metrics</h3><pre>{JSON.stringify(selected.metrics,null,2)}</pre></section><div className="adminActions"><button className={selected.enabled?"danger":"primary"} onClick={toggle}>{selected.enabled?"Disable":"Enable"}</button><button className="quiet" onClick={()=>pick(selected)}>Refresh logs</button></div><section><h3>Logs</h3><div className="logList">{logs.length?logs.map(l=><div className="logRow" key={l.log_id}><strong>{l.level}</strong><span>{l.message}</span><small>{l.created_at}</small></div>):<small>No plugin logs yet.</small>}</div></section><section><h3>Create diagnostic Artifact</h3><textarea value={text} onChange={e=>setText(e.target.value)}/><button className="primary" onClick={artifact}>Save text Artifact</button></section></>}</section></div></div>
}
